FROM node:14.15.4-slim

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG API_URL
ARG APP_ENVIRONMENT
ARG SENTRY_DSN
ARG SENTRY_DISABLED
ARG SENTRY_SAMPLE_RATE
ENV API_URL $API_URL
ENV APP_ENVIRONMENT $APP_ENVIRONMENT
ENV SENTRY_DSN $SENTRY_DSN
ENV SENTRY_SAMPLE_RATE $SENTRY_SAMPLE_RATE
ENV HOST 0.0.0.0
ENV PORT 3000

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
