FROM node:14.15.4-slim

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

RUN --mount=type=secret,id=NUXT_ENV_PUBLIC_URL \
    --mount=type=secret,id=API_URL \
    --mount=type=secret,id=APP_ENVIRONMENT \
    --mount=type=secret,id=SENTRY_DSN \
    --mount=type=secret,id=SENTRY_DISABLED \
    --mount=type=secret,id=SENTRY_SAMPLE_RATE \
    --mount=type=secret,id=GOOGLE_ANALYTICS_ID \
    export NUXT_ENV_PUBLIC_URL=$(cat /run/secrets/NUXT_ENV_PUBLIC_URL_STAGING) && \
    export API_URL=$(cat /run/secrets/API_URL_STAGING) && \
    export APP_ENVIRONMENT=$(cat /run/secrets/APP_ENVIRONMENT_STAGING) && \
    export SENTRY_DSN=$(cat /run/secrets/SENTRY_DSN) && \
    export SENTRY_DISABLED=$(cat /run/secrets/SENTRY_DISABLED) && \
    export SENTRY_SAMPLE_RATE=$(cat /run/secrets/SENTRY_SAMPLE_RATE) && \
    export GOOGLE_ANALYTICS_ID=$(cat /run/secrets/GOOGLE_ANALYTICS_ID)

ENV HOST 0.0.0.0
ENV PORT 3000

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
